server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/charonry/spring-config.git
          ####搜索目录
          search-paths:
            - spring-config
          force-pull: true
          username: 你自己Git账号
          password: 你自己Git密码
          default-label: main
      ####读取分支
      label: main
  rabbitmq:
    host: 192.168.20.129
    username: guest
    password: guest
    port: 5672


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
