server:
  port: 8081
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
     #采样率值介于 0 到 1 之间，1 则表示全部采集
     probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8081  # 在信息列表时显示主机名称
    prefer-ip-address: true  #访问的路径变为IP地址
    #lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    #lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.charon.springcloud.entities